### ISSUE TITLE
quoted text is not displayed in quoting text any more

### ISSUE THREAD

**Issue by bmaz** [medialab/gazouilloire#138]
https://twitter.com/fazealo/status/1501924605522493443

**Comment by boogheta** [comment]
Partly fixed in twitwi's quote handling https://github.com/medialab/twitwi/commit/7054f0a1edb90af2152492567f53334e972bae84 && https://github.com/medialab/twitwi/commit/a8839c455702017a9c4b7fa8e49b9cff3312038f
But there is still a mystery on why the text in ES for this tweet only contains the hashtag and not even the quote's url
